/**
 * Schema definitions for Excel export/import of all entity groups.
 * Each column: { key, label, hint, type? }
 * type: "string" (default) | "number" | "boolean"
 */
export const EXPORT_GROUPS = {
  users: {
    title: "Потребители",
    desc: "Всички регистрирани потребители",
    entity: "User",
    canCreate: false,
    updatableFields: ["role", "menu_group_id"],
    sheets: [{
      sheetName: "Потребители",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор — не редактирайте" },
        { key: "full_name", label: "Име", hint: "Пълно име на потребителя" },
        { key: "email", label: "Имейл", hint: "Имейл адрес за вход" },
        { key: "role", label: "Роля", hint: "Възможни: admin, user, water_owner, advertiser" },
        { key: "menu_group_name", label: "Група", hint: "Име на потребителската група от менюто (оставете празно за без група)" },
        { key: "created_date", label: "Дата на регистрация", hint: "Автоматично генерирана — не редактирайте" },
      ],
    }],
  },
  advertisers: {
    title: "Рекламодатели",
    desc: "Заявки за реклама и рекламодатели",
    entity: "AdSlotRequest",
    sheets: [{
      sheetName: "Рекламодатели",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "ad_slot_name", label: "Банер", hint: "Име на банера" },
        { key: "placement", label: "Позиция", hint: "all, home, session, log_catch, history, sessions, statistics, locations, personal_best, bait_inventory, water_bodies, competitions, sector_reservations, advertise, profile" },
        { key: "advertiser_email", label: "Имейл", hint: "Имейл на рекламодателя" },
        { key: "advertiser_name", label: "Име на рекламодателя", hint: "Име или фирма" },
        { key: "ad_title", label: "Заглавие на реклама", hint: "Текст на заглавието" },
        { key: "ad_description", label: "Описание", hint: "Кратко описание" },
        { key: "ad_cta", label: "Бутон (CTA)", hint: "Текст на бутона, напр. „Вижте оферта“" },
        { key: "website_url", label: "Сайт (URL)", hint: "Линк към сайта" },
        { key: "logo_url", label: "Лого URL", hint: "Линк към лого изображение" },
        { key: "ad_logo_size", label: "Размер на лого", hint: "16x16, 32x16, 48x16 или auto" },
        { key: "ad_bg_class", label: "Цвят на фона", hint: "CSS клас, напр. bg-gradient-to-r from-cyan-600 to-blue-600 или bg-black" },
        { key: "ad_text_class", label: "Цвят на текста", hint: "CSS клас, напр. text-white" },
        { key: "months", label: "Месеци", hint: "Брой месеци", type: "number" },
        { key: "price_per_month", label: "Цена/месец (€)", hint: "Цена на месец в евро", type: "number" },
        { key: "total_price", label: "Обща цена (€)", hint: "Обща цена в евро", type: "number" },
        { key: "countries", label: "Държави", hint: "Разделени със запетая или 'all'" },
        { key: "status", label: "Статус", hint: "pending, approved, rejected, paid, cancelled" },
      ],
    }],
  },
  water: {
    title: "Водоеми",
    desc: "Всички водоеми в системата",
    entity: "WaterBody",
    sheets: [{
      sheetName: "Водоеми",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "name", label: "Име", hint: "Име на водоема" },
        { key: "owner_name", label: "Собственик", hint: "Име на собственика" },
        { key: "contact_phone", label: "Телефон", hint: "Телефон за връзка" },
        { key: "contact_email", label: "Имейл", hint: "Имейл за връзка" },
        { key: "location", label: "Локация", hint: "Адрес или описание на локацията" },
        { key: "latitude", label: "Геогр. ширина", hint: "Десятично число, напр. 42.6977", type: "number" },
        { key: "longitude", label: "Геогр. дължина", hint: "Десятично число, напр. 23.3219", type: "number" },
        { key: "usage_conditions", label: "Условия за ползване", hint: "Правила и условия за риболов" },
        { key: "fish_population", label: "Популация на риби", hint: "Видове риби и тегло" },
        { key: "max_depth", label: "Макс. дълбочина (м)", hint: "В метри", type: "number" },
        { key: "capacity", label: "Капацитет", hint: "Брой сектори или риболовци" },
        { key: "fee_per_person", label: "Такса (€)", hint: "Такса на човек в евро", type: "number" },
        { key: "logo_url", label: "Лого URL", hint: "Линк към лого изображение" },
        { key: "status", label: "Статус", hint: "pending, approved, rejected" },
      ],
    }],
  },
  banners: {
    title: "Банери и слотове",
    desc: "Реклами и рекламни позиции",
    sheets: [
      {
        sheetName: "Реклами",
        entity: "CustomAd",
        columns: [
          { key: "id", label: "ID", hint: "Системен идентификатор" },
          { key: "title", label: "Заглавие", hint: "Заглавие на рекламата" },
          { key: "description", label: "Описание", hint: "Кратко описание" },
          { key: "cta", label: "Бутон (CTA)", hint: "Текст на бутона" },
          { key: "link", label: "Линк", hint: "URL или вътрешен път, напр. /advertise" },
          { key: "logo_url", label: "Лого URL", hint: "Линк към лого" },
          { key: "logo_size", label: "Размер на лого", hint: "16x16, 32x16, 48x16 или auto" },
          { key: "bg_class", label: "Цвят на фона", hint: "CSS клас за фон" },
          { key: "text_class", label: "Цвят на текста", hint: "CSS клас за текст" },
          { key: "is_active", label: "Активна", hint: "Да или Не", type: "boolean" },
          { key: "placement", label: "Позиция", hint: "all, home, session, log_catch и др." },
          { key: "sort_order", label: "Ред", hint: "Номер за подредба", type: "number" },
          { key: "status", label: "Статус", hint: "active или pending_review" },
        ],
      },
      {
        sheetName: "Слотове",
        entity: "AdSlot",
        columns: [
          { key: "id", label: "ID", hint: "Системен идентификатор" },
          { key: "name", label: "Име", hint: "Име на банера" },
          { key: "placement", label: "Позиция", hint: "all, home, session, log_catch и др." },
          { key: "price_per_month", label: "Цена/месец (€)", hint: "Базова цена в евро", type: "number" },
          { key: "is_available", label: "Достъпен", hint: "Да или Не", type: "boolean" },
          { key: "status", label: "Статус", hint: "available или rented" },
        ],
      },
    ],
  },
  prices: {
    title: "Цени по държави",
    desc: "Цени за всички държави (нула ако няма)",
    entity: "AdSlot",
    isPrices: true,
    sheets: [{
      sheetName: "Цени по държави",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "name", label: "Банер", hint: "Име на банера" },
        { key: "placement", label: "Позиция", hint: "Позиция на банера" },
        { key: "price_per_month", label: "Базова цена/месец (€)", hint: "Базова цена в евро", type: "number" },
      ],
    }],
  },
  menugroups: {
    title: "Меню групи",
    desc: "Групи за потребителски менюта",
    entity: "MenuGroup",
    sheets: [{
      sheetName: "Меню групи",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "name", label: "Име", hint: "Име на групата" },
        { key: "description", label: "Описание", hint: "Описание на групата" },
        { key: "menu_items", label: "Менюта", hint: "Пътища, разделени със запетая (напр. /, /active-session, /log-catch)" },
        { key: "status", label: "Статус", hint: "active или inactive" },
      ],
    }],
  },
  languages: {
    title: "Езици",
    desc: "Поддържани езици в приложението",
    entity: "AppLanguage",
    sheets: [{
      sheetName: "Езици",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "code", label: "Код", hint: "ISO код, напр. bg, en, de" },
        { key: "name", label: "Име", hint: "Име на езика (на английски)" },
        { key: "native_name", label: "Оригинално име", hint: "Име на езика на съответния език" },
        { key: "is_active", label: "Активен", hint: "Да или Не", type: "boolean" },
        { key: "sort_order", label: "Ред", hint: "Номер за подредба", type: "number" },
      ],
    }],
  },
  competitions: {
    title: "Състезания",
    desc: "Риболовни състезания",
    entity: "Competition",
    sheets: [{
      sheetName: "Състезания",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "title", label: "Заглавие", hint: "Заглавие на състезанието" },
        { key: "water_body_id", label: "Водоем ID", hint: "ID на водоема" },
        { key: "water_body_name", label: "Водоем", hint: "Име на водоема" },
        { key: "fishing_type", label: "Вид риболов", hint: "feeder, float, carp, predator, match, other" },
        { key: "max_participants", label: "Макс. участници", hint: "Брой участници", type: "number" },
        { key: "max_reserves", label: "Макс. резерви", hint: "Брой резерви", type: "number" },
        { key: "conditions", label: "Условия", hint: "Условия за участие" },
        { key: "prize_fund", label: "Награден фонд", hint: "Описание на наградите" },
        { key: "fee", label: "Такса (€)", hint: "Такса за участие", type: "number" },
        { key: "date", label: "Дата", hint: "Дата и час (ISO формат)" },
        { key: "registration_deadline", label: "Краен срок", hint: "Краен срок за записване (ISO формат)" },
        { key: "status", label: "Статус", hint: "open, closed, completed, cancelled" },
      ],
    }],
  },
  sectoravail: {
    title: "Секторна наличност",
    desc: "Наличност на сектори по водоеми",
    entity: "SectorAvailability",
    sheets: [{
      sheetName: "Секторна наличност",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "water_body_id", label: "Водоем ID", hint: "ID на водоема" },
        { key: "water_body_name", label: "Водоем", hint: "Име на водоема" },
        { key: "date", label: "Начална дата", hint: "Дата (YYYY-MM-DD)" },
        { key: "end_date", label: "Крайна дата", hint: "Крайна дата (YYYY-MM-DD)" },
        { key: "total_sectors", label: "Брой сектори", hint: "Общ брой сектори", type: "number" },
        { key: "fee_per_person", label: "Такса (€)", hint: "Такса на човек", type: "number" },
        { key: "status", label: "Статус", hint: "open или closed" },
      ],
    }],
  },
  sectorres: {
    title: "Секторни резервации",
    desc: "Резервации на сектори",
    entity: "SectorReservation",
    sheets: [{
      sheetName: "Секторни резервации",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "water_body_id", label: "Водоем ID", hint: "ID на водоема" },
        { key: "water_body_name", label: "Водоем", hint: "Име на водоема" },
        { key: "availability_id", label: "Наличност ID", hint: "ID на наличността" },
        { key: "date", label: "Дата", hint: "Дата (YYYY-MM-DD)" },
        { key: "sector_number", label: "Сектор №", hint: "Номер на сектора", type: "number" },
        { key: "reserved_by_name", label: "Резервиран от", hint: "Име на резервиращия" },
        { key: "reserved_by_phone", label: "Телефон", hint: "Телефон за връзка" },
        { key: "fee", label: "Такса (€)", hint: "Такса в евро", type: "number" },
        { key: "payment_status", label: "Статус плащане", hint: "pending, paid, refunded" },
        { key: "status", label: "Статус", hint: "active или cancelled" },
      ],
    }],
  },
  rolerequests: {
    title: "Заявки за роли",
    desc: "Заявки за потребителски роли",
    entity: "RoleRequest",
    sheets: [{
      sheetName: "Заявки за роли",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "requested_role", label: "Заявена роля", hint: "water_owner, advertiser, admin" },
        { key: "user_email", label: "Имейл", hint: "Имейл на потребителя" },
        { key: "user_name", label: "Име", hint: "Име на потребителя" },
        { key: "reason", label: "Основание", hint: "Причина за заявката" },
        { key: "status", label: "Статус", hint: "pending, approved, rejected" },
      ],
    }],
  },
  baseitems: {
    title: "Базови артикули",
    desc: "Захранка и стръв по брандове",
    entity: "BaseItem",
    sheets: [{
      sheetName: "Базови артикули",
      columns: [
        { key: "id", label: "ID", hint: "Системен идентификатор" },
        { key: "name", label: "Име", hint: "Име на артикула" },
        { key: "category", label: "Категория", hint: "groundbait (захранка) или bait (стръв)" },
        { key: "brand", label: "Бранд", hint: "Марка/производител" },
        { key: "shop_url", label: "Линк към търговеца", hint: "URL към магазин" },
        { key: "image_url", label: "Снимка URL", hint: "URL към изображение" },
        { key: "description", label: "Описание", hint: "Кратко описание" },
        { key: "is_active", label: "Активен", hint: "Да или Не", type: "boolean" },
        { key: "sort_order", label: "Ред", hint: "Номер за подредба", type: "number" },
      ],
    }],
  },
};